﻿hydra:
  run:
    dir: ./experiments/${scenario}/${dataset}_${initial_increment}-${increment}_without_exp
  job:
    chdir: true
  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'
class_order: ''
dataset_root: ''
workdir: ''
log_path: metric.json
model_name: ViT-B/16
prompt_template: a photo of a {}.

batch_size: 64
initial_increment: 10
increment: ${initial_increment}
scenario: class
dataset: cifar100
num_workers: 8
train_batch_size: 64
epochs: 15
lr: 0.03
fp16: false
seed: 1993
milestones:
- 4
- 10
beta: 0.5
mix_bias: 0.6
threshold: 0.55
shrinkage: false

use_fsa: true
lambda_anchor: 2

engine:
  lambda_img: 0.5
  sample_num: 0
  sample_noise: 0.25