hydra:
  run:
    dir: ./experiments/${scenario}/${dataset}_${initial_increment}-${increment}
  job:
    chdir: true
  job_logging:
    version: 1
    formatters:
      simple:
        format: "%(message)s"

class_order: ""
dataset_root: "/kaggle/working/RAPF/data/CUB_200_2011"
dataset: "cub200"
workdir: ""
log_path: "metric.json"
model_name: "ViT-B/16"

batch_size: 64
train_batch_size: 64
num_workers: 16
initial_increment: 20
increment: ${initial_increment}
scenario: "class"
epochs: 10
lr: 0.01
fp16: false
seed: 1993
beta: 4.0
mix_bias: 0.6
threshold: 0.65
shrinkage: false

dropout: 0.1
lambda_img: 0.5
lambda_txt: 1
replay_alpha: 0.25
sample_num: 0
stat: 0.95
sample_noise: 0.3
templates:
  - a photo of a {} bird.
  - a photo of the {} bird.
  - a close-up photo of a {} bird.
  - a close-up photo of the {} bird.
