hydra:
  run:
    dir: ./experiments/${dataset}_${initial_increment}-${increment}
  job:
    chdir: true

class_order: ""
dataset_root: ""
log_path: "metric.json"
model_name: "ViT-B/16"
prompt_template: "a good photo of a {}."

batch_size: 64
initial_increment: 100  
increment: 10
dataset: "imagenet_R"
num_workers: 16
train_batch_size: 64
epochs: 10
lr: 0.01
fp16: false
seed: 1993
beta: 2 
threshold: 0.65
shrinkage: True

lambda_img: 2.0
lambda_txt: 2.0
sample_num: 0
stat: 0.9
sample_noise: 0.25
templates:
  - itap of a {}.
  - a bad photo of the {}.
  - a origami {}.
  - a photo of the large {}.
  - a {} in a video game.
  - art of the {}..
  - a photo of the small {}.
